userType = None
currentUser = None
isTrustLogin = False
trustkey = None
trustVal = None
forgotpassotp = None
forgotpassotptime = None
userphone = None
encyptionkey = b'5mgdtkgjMcGj2hBGXAIqA7fcaEeS0_LAT4N8wRNF0ZA='
adminLogin = False
